UserSigning/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import authenticate,login,logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'signing'

urlpatterns = [
   url(r'^$', views.initialRedirection, kwargs=None, name='initial'),
   url(r'^login/$', views.login_view, kwargs=None, name='login'),
   url(r'^register/$', views.signup_view, kwargs=None, name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollzo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("UserSigning.urls")),
    url(r'^user/',include("userProfile.urls"))
]

userProfile/urls.py
from django.conf.urls import url
from . import views

app_name = 'profile'

urlpatterns=[
   url(r'^(?P<user_name>[a-z]+)/$', views.profile_view, kwargs=None, name='userprofileview'),
   url(r'^(?P<user_name>[a-z]+)/interests/$',views.interest,name='interests'),
   url(r'^(?P<user_name>[a-z]+)/newsfeed/$',views.feed,name='feed'),
   url(r'^(?P<user_name>[a-z]+)/following/$',views.following,name='following'),
   url(r'^(?P<user_name>[a-z]+)/followers/$',views.followers,name='followers'),
   url(r'^(?P<user_name>[a-z]+)/people/$',views.people,name='people'),
   url(r'^logout',views.logout_view,name='logout'),
   url(r'^ajaxrequest/followinterest/$',views.followInterest),
   url(r'^ajaxrequest/changecover/$',views.changecover),
   url(r'^ajaxrequest/followuser/$',views.followuser),
   url(r'^ajaxrequest/vote/$',views.vote),
   url(r'^ajaxrequest/delete/$',views.deletepoll),
   url(r'^editprofile/cover/$',views.cover,name='cover'),
   url(r'^editprofile/profile/$',views.edit,name='edit'),
   url(r'^new-poll/add/$',views.newPoll,name='new-poll'),
   url(r'^new-poll/add-choices/$',views.newPollChoices,name='new-poll-choices'),
]

userProfile/models.py
from django.db import models
from django.contrib.auth.models import User

# Aesthetic
class CoverPhoto(models.Model):
    name = models.CharField(max_length=100,blank=True,default='')
    cover_photo = models.ImageField(upload_to='cover_photos/')
    def __str__(self):
        return self.name

# User Essentials
class Interest(models.Model):
    interest_name = models.CharField(max_length = 100)

    def __str__(self):
        return self.interest_name

class PollzoUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, to_field=None)
    profile_pic = models.FileField(verbose_name=None, name=None, upload_to='profile_pic/', storage=None)
    interests = models.ManyToManyField(Interest, related_name=None, related_query_name=None, limit_choices_to=None, symmetrical=None, through=None, through_fields=None, db_constraint=True, db_table=None, swappable=True)
    desciption = models.CharField(max_length = 1000, default = '', blank=True)
    following = models.ManyToManyField('self',blank=True,symmetrical=False)
    cover_photo = models.ForeignKey(CoverPhoto,blank=True,null=True)
    def __str__(self):
        return self.user.username

class Question(models.Model):
    question_text = models.CharField(max_length=1000)
    created_by = models.ForeignKey(PollzoUser,on_delete=models.CASCADE)
    #voted_by = models.ManyToManyField(PollzoUser,through='UserVotes')
    interests = models.ManyToManyField(Interest)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    choice_text = models.CharField(max_length=500)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    vote_Count = models.IntegerField()

    def __str__(self):
        return self.choice_text

class UserVotes(models.Model):
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice,on_delete=models.CASCADE)
    voted_by_user = models.ForeignKey(PollzoUser,on_delete=models.CASCADE)

    def __str__(self):
        return self.question.question_text +'-' +self.choice.choice_text+'-'+self.voted_by_user.user.username

userProfile/forms.py
from django.forms import ModelForm
from .models import Question

class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text','interests']
        help_texts = {
            'interests':'select multiple choices by pressing CTRL'
        }

userProfile/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import PollzoUser, Interest, CoverPhoto, Question, Choice, UserVotes
from django.contrib.auth.models import User
from django.contrib.auth import logout,login,authenticate
from django.contrib.auth.decorators import login_required
#from forms import QuestionForm
# Create your views here.
@login_required
def profile_view(request,user_name):
    title = user_name
    context = {
    "title":title
    }
    context["profileUser"] = user = User.objects.get(username = user_name)
    context["profile"] = profile = PollzoUser.objects.get(user=user)
    context["currentUserName"] = request.user.username
    context["followers"] = PollzoUser.objects.filter(following=profile).count()
    context["following"] = profile.following.all().count()

    if Question.objects.filter(created_by=profile).count() != 0:
        context["questions"] = questions = Question.objects.filter(created_by=profile)
        question_choices = []
        for question in questions:
            obj_to_send = {
               'question':question,
               'choices':[]
            }
            for choice in Choice.objects.filter(question = question):
                obj_to_send['choices'].append(choice)
            question_choices.append(obj_to_send)
        context['question_choices'] = question_choices
        votes_by_me = UserVotes.objects.filter(voted_by_user = PollzoUser.objects.get(user=request.user))
        my_choices = []
        for votes in votes_by_me:
            my_choices.append(votes.choice)
        context['my_choices'] = my_choices


    browsing_user = PollzoUser.objects.get(user=request.user)
    if profile in browsing_user.following.all():
        context["isFollowing"] = True
    if request.user == user:
        context["isSameUser"] = True
    return render(request,"profile/profile.html", context, content_type=None, status=None, using=None)



@login_required
def interest(request,user_name):
    context = {
    "title":"Interests",
    "all_interests":Interest.objects.all()
    }

    context["currentUser"] = request.user.first_name
    context["currentUserName"] = request.user.username
    requesting_user = get_object_or_404(User,username=user_name)
    context["currentPollzoUser"] = PollzoUser.objects.get(user=request.user)
    context["profileUser"] = requesting_user
    context["currentPollzoProfile"] = PollzoUser.objects.get(user=requesting_user)
    if request.user == requesting_user:
        context["isSameUser"] = True

    return render(request,"profile/interests.html",context)

@login_required
def followInterest(request):
    int_id = request.GET['intId']
    currentUser = PollzoUser.objects.get(user=request.user)
    interestToAdd = Interest.objects.get(pk=int_id)
    if interestToAdd in currentUser.interests.all():
        currentUser.interests.remove(interestToAdd)
        return HttpResponse(2)
    else:
        currentUser.interests.add(interestToAdd)
        return HttpResponse(1)
@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('signing:initial'))
@login_required
def cover(request):
    title = "Change cover"
    context = {
        "title":title,
        "coverphotos":CoverPhoto.objects.all()
    }
    context["profileUser"] = user = request.user
    context["profile"] = profile = PollzoUser.objects.get(user=user)
    context["currentUserName"] = request.user.username
    return render(request,"profile/cover.html",context)
@login_required
def changecover(request):
    photo_id = request.GET.get("photoId",1);
    photo = CoverPhoto.objects.get(id=photo_id)
    user = PollzoUser.objects.get(user=request.user)
    user.cover_photo = photo
    user.save()
    return HttpResponse(photo.cover_photo.url)

def followuser(request):
    userid = request.GET['userId']
    userToFollow = PollzoUser.objects.get(id=userid)
    currentUser = PollzoUser.objects.get(user=request.user)
    if userToFollow in currentUser.following.all():
        currentUser.following.remove(userToFollow)
        currentUser.save()
        return HttpResponse(2)
    else:
        currentUser.following.add(userToFollow)
        currentUser.save()
        return HttpResponse(1)
@login_required
def edit(request):
    context = {
      "title":"Edit Profile"
    }
    context["currentUserName"] = request.user.username
    context['currentUser'] = user = request.user
    context['currentProfile'] = profile = PollzoUser.objects.get(user=request.user)
    if request.POST:
        fname = request.POST['fname']
        lname = request.POST['lname']
        desc = request.POST['desc']
        prof = None
        if request.FILES:
            prof = request.FILES['prof']
        user.first_name = fname
        if lname:
            user.last_name = lname
        if desc:
            profile.desciption = desc
        if prof:
            profile.profile_pic = prof
        user.save()
        profile.save()
        return HttpResponseRedirect(reverse('profile:userprofileview',kwargs={'user_name':user.username}))
    return render(request,"profile/edit.html",context)

@login_required
def newPoll(request):
    context = {
        "title":"Add new Poll",
        "currentUserName":request.user.username,
        "currentUser":request.user,
        "profile":PollzoUser.objects.get(user=request.user),
        "interests":Interest.objects.all(),
        "form":QuestionForm()

    }
    return render(request,"profile/new-poll.html",context)
@login_required
def newPollChoices(request):
        question_text = request.POST['question']
        interests = request.POST.getlist('int')
        if not Question.objects.filter(question_text=question_text).exists():
            new_poll = Question(question_text = question_text,created_by=PollzoUser.objects.get(user=request.user))
            new_poll.save()
            for interestId in interests:
                new_poll.interests.add(Interest.objects.get(pk=interestId))
            new_poll.save()
        else:
            new_poll = Question.objects.get(question_text=question_text)
        if 'choice_item' in request.POST:
            new_poll.choice_set.create(choice_text=request.POST['choice_item'],vote_Count=0)

        context = {
            "title":"Add new Poll",
            "currentUserName":request.user.username,
            "currentUser":request.user,
            "profile":PollzoUser.objects.get(user=request.user),
            "interests":Interest.objects.all(),
            "question":new_poll

        }
        return render(request,"profile/new-poll-choices.html",context)

def vote(request):
    qID = request.GET['qID']
    cID = request.GET['cID']
    voting_user = PollzoUser.objects.get(user=request.user)

    uVote = UserVotes(question=Question.objects.get(id=qID),choice = Choice.objects.get(id=cID),voted_by_user=voting_user)
    if uVote not in UserVotes.objects.all():
        if not UserVotes.objects.filter(voted_by_user=voting_user,question=Question.objects.get(id=qID)):
            uVote.save()
            choice_chosen = Choice.objects.get(id=cID)
            choice_chosen.vote_Count += 1
            choice_chosen.save()
            return HttpResponse(choice_chosen.vote_Count)
    return HttpResponse(0)
@login_required
def feed(request,user_name):
    if user_name != request.user.username:
        return HttpResponseRedirect(reverse('profile:feed',kwargs={'user_name':request.user.username}))
    else:
        context = {
            'title':user_name,
            'currentUserName': user_name,
            'interests':Interest.objects.all()
        }
        newsFeed = []
        currentUser = PollzoUser.objects.get(user=request.user)
        for interest in currentUser.interests.all():
            for question in Question.objects.filter(interests = interest):
                if question not in newsFeed:
                    newsFeed.append(question)
        following = currentUser.following.all()
        for user in following:
            for question in Question.objects.filter(created_by=user):
                if question not in newsFeed:
                    newsFeed.append(question)

        if len(newsFeed) != 0:
            context['newsFeed'] = newsFeed
        context['currentUser'] = currentUser
        votes_by_me = UserVotes.objects.filter(voted_by_user = PollzoUser.objects.get(user=request.user))
        my_choices = []
        for votes in votes_by_me:
            my_choices.append(votes.choice)
        context['my_choices'] = my_choices
        return render(request,'profile/newsfeed.html',context)


def deletepoll(request):
    qId = request.GET['qID']
    question = Question.objects.get(pk=qId)
    if question.created_by.user == request.user:
        question.delete()
        return HttpResponse(1)
    return HttpResponse(0)

@login_required
def following(request,user_name):
    context = {
    'message' : 'People followed by '+str(user_name),
      'title':str(user_name),
      'currentUserName':request.user.username
    }
    currentUser = User.objects.get(username=user_name)
    user = PollzoUser.objects.get(user = currentUser)
    context['user_following'] = user.following.all()
    context['i_am_following'] = PollzoUser.objects.get(user=request.user).following.all()
    return render(request,'profile/following.html',context)

@login_required
def followers(request,user_name):
    context = {
      'message' : 'People following '+str(user_name),
      'title':'People following '+str(user_name),
      'currentUserName':request.user.username
    }
    currentUser = User.objects.get(username=user_name)

userProfile/templates/profile/cover.html
{% extends 'profile/profilebase.html' %}
{% load staticfiles %}

{% block content %}

<div class="container-fluid cover-container">

  <div class="row">
    <div class="col-xs-12 header" style="background-image:url({{profile.cover_photo.cover_photo.url}})">
      <div class="profile-photo">
        <img src="{{profile.profile_pic.url}}" alt="">
      </div>
      <h2>{{profileUser.first_name}}&nbsp;{{profileUser.last_name}}</h2>
      <p style="color:white; text-align:center">{{profile.desciption}}</p>
    </div>
  </div>
  <br>
  <h1>Choose a cover photo.</h1>
  <br>
  <div class="container">
  <div class="row">
    {% for photo in coverphotos %}
      <div class="col-md-3 col-sm-4 col-xs-12 tile-cover">
        <div class="panel panel-primary photo-tile" data-id={{photo.id}}>
          <div class="panel-heading">
            {{photo.name}}
          </div>
          <div class="panel-body" style="background-image:url({{photo.cover_photo.url}})">

          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  </div>

</div>
{% endblock %}

userProfile/templates/profile/following.html
{% extends 'profile/profilebase.html' %}
{% load staticfiles %}
{% block people-active %}"active"{% endblock %}
{% block content %}
<style media="screen">
  .bg{
    width: 100%;
    height: 100vh;
    position: fixed;
    background-position: center center;
    background-size: cover;
    background-repeat: no-repeat;
    z-index: -1000;
  }
</style>
<div class="bg" style="background-image:url({% static 'images/intbg.jpg' %})"></div>

<div class="container container-people">
  <br>
  <h1 style="color:white;text-align:center">{{message}}</h1>
  <br>
  {% for user in user_following %}
  <div class="row">
  <div class="col-sm-offset-2 col-sm-8 col-md-offset-3 col-md-6 col-xs-12">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-xs-3 img" >
              <img src="{{user.profile_pic.url}}" alt="">
          </div>
          <div class="col-xs-5 name">
            <a href="{% url 'profile:userprofileview' user_name=user.user.username %}">{{user.user.first_name}}&nbsp;{{user.user.last_name}}</a>
          </div>
          <div class="col-xs-4">
            {% if user in i_am_following %}
            <button class="btn btn-danger f-btn" data-id={{user.id}}><span class="glyphicon glyphicon-remove-sign"></span>&nbsp; Unfollow</button>
            {% else %}
            <button class="btn btn-primary f-btn" data-id={{user.id}}><span class="glyphicon glyphicon-ok-sign"></span>&nbsp; Follow</button>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

userProfile/templates/profile/new-poll.html
{% extends 'profile/profilebase.html' %}
{% load staticfiles %}

{% block content %}

   <div class="container-fluid add-poll" style="background-image:url({{profile.cover_photo.cover_photo.url}})">
     <br>
     <br>
     <div class="row">
       <div class="col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-6 col-xs-12 panel-cover">
         <div class="panel panel-primary">
           <div class="panel-heading">
             Add a new poll
           </div>
           <div class="panel-body">
             <form class="" action="{% url 'profile:new-poll-choices' %}" method="post">


             {% csrf_token %}

             <div class="form-group">
               <label for="question">
                 Question
               </label>
               <input type="text" name="question" value="" class="form-control input-lg" minlength="10">
             </div>
             <div class="from-group">
               <label for="int">Topics</label>
               <br>
               <select class="selectpicker" name="int" multiple required>
                  {% for interest in interests %}
                  <option value="{{interest.id}}">{{interest.interest_name}}</option>
                  {% endfor %}
               </select>
             </div>
             <br>
             
             <button type="submit" class="btn btn-primary btn-lg" name="button">Next</button>
             <br>
              </form>
           </div>
         </div>
       </div>
     </div>

   </div>
{% endblock %}

userProfile/templates/profile/newsfeed.html
{% extends 'profile/profilebase.html' %}
{% load staticfiles %}
{% block feed-active %}"active"{% endblock %}

{% block content %}
<style media="screen">
  .back{
    background-image: url({% static 'images/bg2.jpg'%});
    background-position: center center;
    background-repeat: no-repeat;
    background-size: cover;
    width: 100%;
    height: 100vh;
    position: fixed;
    z-index: -1000;
  }
</style>
<div class="back"></div>
<div class="container-fluid feed">
  <div class="container">
      <br>
      <div class="row">
        <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12 panel-cover">
          <div class="panel panel-primary">
            <div class="panel-heading">
              Add a new poll
            </div>
            <div class="panel-body">
              <form class="" action="{% url 'profile:new-poll-choices' %}" method="post">


              {% csrf_token %}

              <div class="form-group">
                <label for="question">
                  Question
                </label>
                <input type="text" name="question" value="" class="form-control input-lg" minlength="10">
              </div>
              <div class="from-group">
                <label for="int">Topics</label>
                <br>
                <select class="selectpicker" name="int" multiple required>
                   {% for interest in interests %}
                   <option value="{{interest.id}}">{{interest.interest_name}}</option>
                   {% endfor %}
                </select>
              </div>
              <br>

              <button type="submit" class="btn btn-primary btn-lg" name="button">Next</button>
              <br>
               </form>
            </div>
          </div>
        </div>
      </div>

      <!--newsfeed-->

      {% if newsFeed %}

      {% for question in newsFeed %}
      <div class="row">
         <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12 newsfeed-item">
           <div class="panel panel-primary">

             <div class="panel-heading">
               <strong>{{question.question_text}}</strong>
             </div>

             <div class="panel-body">
               {% for choice in question.choice_set.all %}
               <div class="choice-box" {% if choice in my_choices %} style='background-color:#697f4d;color:white;' {% endif %} data-q={{question.id}} data-c={{choice.id}}>
                 <div class="choice-text">
                   {{choice.choice_text}}
                 </div>
                 <div class="vote-count">
                   {{choice.vote_Count}}
                 </div>
               </div>
               {% endfor %}
             </div>

             <div class="panel-footer">
               {% if currentUserName == question.created_by.user.username%}
               <button class="btn-default btn delete-poll-btn" data-q={{question.id}}><span class="glyphicon glyphicon-trash"></span></button>
               {% else %}
               <a href="{% url 'profile:userprofileview' user_name=question.created_by.user.username %}">created by @{{question.created_by.user.username}}</a>
               {% endif %}
             </div>
           </div>
         </div>
      </div>
      {% endfor %}
      <br>
      <h3 style="text-align:center;color:white;padding:10px; background-color:rgba(0,0,0,0.4);"> No more items </h3>
      {% else %}
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8 col-xs-12 col-md-offset-3 col-md-6">
          <div class="panel panel-default">
            <div class="panel-body">
              <h2>You don't have any item in your news feed</h2>
              <a href="{% url 'profile:interests' user_name=currentUserName %}"><button class="btn btn-primary">Follow Interests</button></a>
              &nbsp;
              or
              &nbsp;
              <button class="btn btn-primary ">Follow People</button>
            </div>
          </div>
        </div>
      </div>

      {% endif %}


  </div>
</div>

{% endblock %}

userProfile/templates/profile/profile.html
{% extends 'profile/profilebase.html' %}
{% load staticfiles %}
{% block profile-active %}"active"{% endblock %}
{% block content %}
  <style media="screen">
    body{

      padding-bottom: 70px;
    }
  </style>
  <div class="container-fluid profile-container" style="padding-bottom:70px;">
    <div class="row">
      <div class="col-xs-12 header" style="background-image:url({{profile.cover_photo.cover_photo.url}})">
        {% if isSameUser %}
        <a href="{% url 'profile:cover'%}" class="change-cover"><span class="glyphicon glyphicon-camera"></span>&nbsp;Change cover</a>
        {% else %}
        {% if not isFollowing %}
        <button type="button" class="btn btn-primary btn-lg f-btn" data-id={{profile.id}} name="button"><span class="glyphicon glyphicon-ok-sign"></span>&nbsp;Follow</button>
        {% else %}
        <button type="button" class="btn btn-danger btn-lg f-btn" data-id={{profile.id}} name="button"><span class="glyphicon glyphicon-remove-sign"></span>&nbsp;Unfollow</button>
        {% endif %}
        {% endif %}
        <div class="profile-photo">
          <img src="{{profile.profile_pic.url}}" alt="">
        </div>
        <h2>{{profileUser.first_name}}&nbsp;{{profileUser.last_name}}</h2>
        <p style="color:white; text-align:center">{{profile.desciption}}</p>
      </div>

    </div>
    <div class="row">
      <div class="col-sx-12  hidden-md hidden-lg detail">
        {% if isSameUser %}
           <a href="{% url 'profile:new-poll' %}"><button class="btn btn-danger btn-lg" type="button"><span class="glyphicon glyphicon-plus"></span>&nbsp;New Poll</button></a>

           <a href="{% url 'profile:edit' %}"><button type="button" class="btn btn-primary btn-lg" name="button"><span class="glyphicon glyphicon-sunglasses"></span>&nbsp;Edit Profile</button></a>

           <a href="{% url 'profile:interests' user_name=profileUser.username%}"><button class="btn btn-primary btn-lg" type="button"><span class="glyphicon glyphicon-glass"></span>&nbsp;Interests</button></a>
        {% endif %}

        <a href="{% url 'profile:followers' user_name=currentUserName %}"><button type="button" class="btn btn-success btn-lg" name="button">{{followers}} followers</button></a>
        
        <a href="{% url 'profile:following' user_name=currentUserName %}"><button type="button" class="btn btn-success btn-lg" name="button">{{following}} following</button></a>
      </div>
    </div>
    <div class="row">

      <div class="side-pane col-md-3 hidden-xs hidden-sm">
        <br>
        {% if isSameUser %}
           <a href="{% url 'profile:new-poll' %}"><button class="btn btn-danger btn-lg" type="button"><span class="glyphicon glyphicon-plus"></span>&nbsp;New Poll</button></a>
           <br>
           <a href="{% url 'profile:edit' %}"><button type="button" class="btn btn-primary btn-lg" name="button"><span class="glyphicon glyphicon-sunglasses"></span>&nbsp;Edit Profile</button></a>
           <br>
           <a href="{% url 'profile:interests' user_name=profileUser.username%}"><button class="btn btn-primary btn-lg" type="button"><span class="glyphicon glyphicon-glass"></span>&nbsp;Interests</button></a>
        {% endif %}
        <br>
        <a href="{% url 'profile:followers' user_name=currentUserName %}"><button type="button" class="btn btn-success btn-lg" name="button">{{followers}} followers</button></a>
        <br>
        <a href="{% url 'profile:following' user_name=currentUserName %}"><button type="button" class="btn btn-success btn-lg" name="button">{{following}} following</button></a>
      </div>

      <div class="col-md-9 col-sm-12 question main-profile-container">
        <br>
        <br>
        {% if questions %}
        {% if isSameUser %}
        <a style="text-align:center;display:block;">Questions created by you.</a>
        {% else %}
        <a style="text-align:center;display:block;">Questions created by {{profileUser.first_name}}</a>
        {% endif %}
        <br>

        <div class="q-container">
            {% for question in question_choices %}
            <div class="row">
              <div class="col-xs-12">
                <div class="panel panel-primary">
                  <div class="panel-heading">
                    <h5>{{question.question.question_text}}</h5>
                  </div>
                  <div class="panel-body">
                    {% for choice in question.choices %}
                    <div class="choice-box" {% if choice in my_choices %} style='background-color:#697f4d;color:white;' {% endif %}data-q={{question.question.id}} data-c={{choice.id}}>
                      <div class="choice-text">
                        {{choice.choice_text}}
                      </div>
                      <div class="vote-count">
                        {{choice.vote_Count}}
                      </div>
                    </div>
                    {% endfor %}
                  </div>
                  <div class="panel-footer">
                    <button class="btn-default btn delete-poll-btn" data-q={{question.question.id}}><span class="glyphicon glyphicon-trash"></span></button>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>

        {% else %}
        {% if isSameUser %}
        <div class="row">
          <div class="col-xs-12">
            <div class="panel panel-danger">
              <div class="panel-heading">
                You don't have any polls yet
              </div>
              <div class="panel-body">
                <a href="{% url 'profile:new-poll' %}"><button class="btn btn-danger btn-lg" style="margin:0 auto; display:block">Add a poll</button></a>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <a>User have not created any poll yet</a>
        {% endif %}
        {% endif %}
      </div>

    </div>
  </div>
{% endblock %}

userProfile/templates/profile/profilebase.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style-profile.min.css' %}">
    <title>{{title}}</title>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/css/bootstrap-select.min.css">
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'signing:initial' %}">pollzo</a>
      </div>
      <div class="collapse navbar-collapse" id="Navbar">
        <ul class="navbar-nav nav">
          <li class={% block profile-active %}{% endblock %}>
            <a href="/user/{{currentUserName}}/"><span class="glyphicon glyphicon-user"></span> &nbsp;Profile</a>
          </li>
          <li class={% block feed-active %}{% endblock %}>
            <a href="{% url 'profile:feed' user_name=currentUserName %}"><span class="glyphicon glyphicon-list"></span> &nbsp;News Feed</a>
          </li>
          <li class={% block people-active %}{% endblock %}>
            <a href="{% url 'profile:people' user_name=currentUserName %}"><span class="glyphicon glyphicon-search"></span> &nbsp;Find People</a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'profile:logout' %}"><span class="glyphicon glyphicon-off"></span> &nbsp;Logout</a></li>
        </ul>
      </div>
    </div>
  </nav>
  <br>

  {%block content%}
  {% endblock %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="{% static 'js/main.js' %}" charset="utf-8"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.2/js/bootstrap-select.min.js" charset="utf-8"></script>
  <script type="text/javascript">
     $('.selectpicker').selectpicker();
  </script>
  </body>
</html>