UserSigning/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import authenticate,login,logout
from django.conf import settings
from django.conf.urls.static import static

app_name = 'signing'

urlpatterns = [
   url(r'^$', views.initialRedirection, kwargs=None, name='initial'),
   url(r'^login/$', views.login_view, kwargs=None, name='login'),
   url(r'^register/$', views.signup_view, kwargs=None, name='signup')
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pollzo/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include("UserSigning.urls")),
    url(r'^user/',include("userProfile.urls"))
]

UserSigning/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

UserSigning/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.models import User
from userProfile.models import PollzoUser
# Create your views here.
def initialRedirection(request):
    return HttpResponseRedirect(reverse('signing:login'))


def login_view(request):
    title = 'pollzo'
    context = {
      "title":title
    }
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('profile:userprofileview',kwargs={'user_name':request.user.username}))
    if request.POST:
        user_name = request.POST['user_name']
        pass_word = request.POST['pass_word']
        user = authenticate(username=user_name,password=pass_word)
        if user is not None:
            login(request,user)
            return HttpResponseRedirect(reverse('profile:userprofileview',kwargs={'user_name':request.user.username}))
        else:
            context['message'] = 'Invalid Credentials'
    return render(request,"signing/login.html", context, content_type=None, status=None, using=None)

def signup_view(request):
    title = 'SignUp'
    context = {
      'title':title
    }
    if request.POST:
        user_name = request.POST['user_name']
        first_name = request.POST['first_name']
        email = request.POST['email']
        pass_word = request.POST['pass_word']
        profile_pic = request.FILES['prof']

        if User.objects.filter(username=user_name).exists():
            context["message"] = "User already exists with this username!"
        else:
            new_user = User.objects.create_user(user_name, email=email, password=pass_word)
            new_user.first_name = first_name
            new_user.save()
            new_user_profile = PollzoUser(user=new_user,profile_pic=profile_pic)
            new_user_profile.save(force_insert=False, force_update=False, using=None, update_fields=None)
            login(request, new_user, backend=None)
            return HttpResponseRedirect(reverse('profile:userprofileview',kwargs={'user_name':user_name}))
    return render(request,"signing/signup.html", context, content_type=None, status=None, using=None)

UserSigning/templates/signing/login.html
{% extends 'signing/signing-base.html' %}
{% load staticfiles %}

{% block linkTitle %}Sign Up{% endblock %}
{% block linkUrl %}{% url 'signing:signup' %}{% endblock %}
{% block content %}

<div class="container-fluid content-wrap-login" style="background-image:url({% static 'images/people.jpg'%})">
  <br>
  <br>
  <br>

  <div class="row">
    <div class="col-sm-offset-3 col-sm-6 col-md-offset-4 col-md-4">
      <div class="panel panel-primary">
        <div class="panel-heading">
          Know what your fellow humans have opinion about
        </div>
        <div class="panel-body">
          <p>{{message}}</p>
          <form action="{% url 'signing:login' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                <input type="text" id="username" name="user_name" class="form-control input-lg" required placeholder="Username">
              </div>
            </div>
            <div class="form-group">
              <div class="input-group">
                <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
                <input id="password" type="password" name="pass_word" class="form-control input-lg" required placeholder="Password">
              </div>
            </div>
            <button type="submit" class="btn btn-primary btn-lg" >Login</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

UserSigning/templates/signing/signing-base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style-login.min.css' %}">
    <title>{{title}}</title>
  </head>
  <body>

  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Navbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'signing:initial' %}">pollzo</a>
      </div>
      <div class="collapse navbar-collapse" id="Navbar">
        <ul class="nav navbar-nav">
          <li><a href="#"><span class="glyphicon glyphicon-camera"></span> &nbsp; Developer portfolio</a></li>
          <li><a href="#"><i class="icon-github"></i> github</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% block linkUrl %}{% endblock %}"><span class="glyphicon glyphicon-user"></span> &nbsp; {% block linkTitle%}{% endblock %}</a></li>
        </ul>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock %}

  <nav class="navbar navbar-inverse navbar-fixed-bottom">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <li><a href="/admin">admin? login here</a></li>
      </ul>
    </div>
  </nav>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

UserSigning/templates/signing/signup.html
{% extends 'signing/signing-base.html' %}
{% load staticfiles %}
{% block linkTitle %}login{% endblock %}
{% block linkUrl %}{% url 'signing:login' %}{% endblock %}

{% block content %}
  <div class="container-fluid content-wrap-signup" style="background-image:url({% static 'images/bg2.jpg' %})">
      <br>
      <br>

      <div class="row">
        <div class="col-md-offset-3 col-md-6 col-sm-12">
          <div class="panel panel-primary">
            <div class="panel-heading">
              Regiter as a new pollzo user.
            </div>
            <div class="panel-body">
              <p>{{message}}</p>
              <form action="{% url 'signing:signup' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <div class="form-group">
                  <label for="username" class="sr-only">User Name</label>
                  <input type="text" class="form-control input-lg" name="user_name" id="username" value="" placeholder="Select a user name" pattern="^[A-Za-z]+$" aria-describedby='helpUserName' required>
                  <span id="helpUserName" class="form-text text-muted">should consist of letters only</span>
                </div>
                <div class="form-group">
                  <label for="fname" class="sr-only">First Name</label>
                  <input type="text" class="form-control input-lg" name="first_name" id="fname" value="" placeholder="First name" required>
                </div>
                <div class="form-group">
                  <label for="email" class="sr-only">Email</label>
                  <input type="email" class="form-control input-lg" name="email" id="email" value="" placeholder="Email" required>
                </div>
                <div class="form-group">
                  <label for="password" class="sr-only">Password</label>
                  <input type="password" minlength=8 class="form-control input-lg" name="pass_word" id="password" value="" placeholder="Choose a password" required>
                </div>
                <div class="form-group">
                  <label for="prof">Select a profile picture</label>
                  <input type="file" class="form-control" name="prof" id="prof" accept='image/*' required>
                </div>

                <button type="submit" class='btn btn-primary btn-lg' name="button">Sign Up</button>
              </form>
            </div>
          </div>
        </div>
      </div>
  </div>
{% endblock %}